/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface Bc76a9d52929cab7a147ca7b5c527430200Response
 */
export interface Bc76a9d52929cab7a147ca7b5c527430200Response {
    /**
     * 
     * @type {LoginResponse}
     * @memberof Bc76a9d52929cab7a147ca7b5c527430200Response
     */
    data?: LoginResponse;
    /**
     * 
     * @type {boolean}
     * @memberof Bc76a9d52929cab7a147ca7b5c527430200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Bc76a9d52929cab7a147ca7b5c527430200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Bc76a9d52929cab7a147ca7b5c527430200Response interface.
 */
export function instanceOfBc76a9d52929cab7a147ca7b5c527430200Response(value: object): value is Bc76a9d52929cab7a147ca7b5c527430200Response {
    return true;
}

export function Bc76a9d52929cab7a147ca7b5c527430200ResponseFromJSON(json: any): Bc76a9d52929cab7a147ca7b5c527430200Response {
    return Bc76a9d52929cab7a147ca7b5c527430200ResponseFromJSONTyped(json, false);
}

export function Bc76a9d52929cab7a147ca7b5c527430200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bc76a9d52929cab7a147ca7b5c527430200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Bc76a9d52929cab7a147ca7b5c527430200ResponseToJSON(json: any): Bc76a9d52929cab7a147ca7b5c527430200Response {
    return Bc76a9d52929cab7a147ca7b5c527430200ResponseToJSONTyped(json, false);
}

export function Bc76a9d52929cab7a147ca7b5c527430200ResponseToJSONTyped(value?: Bc76a9d52929cab7a147ca7b5c527430200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LoginResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

