/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscountPolicy
 */
export interface DiscountPolicy {
    /**
     * 
     * @type {number}
     * @memberof DiscountPolicy
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof DiscountPolicy
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DiscountPolicy
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the DiscountPolicy interface.
 */
export function instanceOfDiscountPolicy(value: object): value is DiscountPolicy {
    return true;
}

export function DiscountPolicyFromJSON(json: any): DiscountPolicy {
    return DiscountPolicyFromJSONTyped(json, false);
}

export function DiscountPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function DiscountPolicyToJSON(json: any): DiscountPolicy {
    return DiscountPolicyToJSONTyped(json, false);
}

export function DiscountPolicyToJSONTyped(value?: DiscountPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

