/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface GetMyStudents200Response
 */
export interface GetMyStudents200Response {
    /**
     * 
     * @type {Array<Student>}
     * @memberof GetMyStudents200Response
     */
    data?: Array<Student>;
    /**
     * 
     * @type {boolean}
     * @memberof GetMyStudents200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetMyStudents200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the GetMyStudents200Response interface.
 */
export function instanceOfGetMyStudents200Response(value: object): value is GetMyStudents200Response {
    return true;
}

export function GetMyStudents200ResponseFromJSON(json: any): GetMyStudents200Response {
    return GetMyStudents200ResponseFromJSONTyped(json, false);
}

export function GetMyStudents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyStudents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StudentFromJSON)),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetMyStudents200ResponseToJSON(json: any): GetMyStudents200Response {
    return GetMyStudents200ResponseToJSONTyped(json, false);
}

export function GetMyStudents200ResponseToJSONTyped(value?: GetMyStudents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StudentToJSON)),
        'didError': value['didError'],
        'error': value['error'],
    };
}

