/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatCardResponse } from './StatCardResponse';
import {
    StatCardResponseFromJSON,
    StatCardResponseFromJSONTyped,
    StatCardResponseToJSON,
    StatCardResponseToJSONTyped,
} from './StatCardResponse';

/**
 * 
 * @export
 * @interface GetTotalStudents200Response
 */
export interface GetTotalStudents200Response {
    /**
     * 
     * @type {StatCardResponse}
     * @memberof GetTotalStudents200Response
     */
    data?: StatCardResponse;
    /**
     * 
     * @type {boolean}
     * @memberof GetTotalStudents200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetTotalStudents200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the GetTotalStudents200Response interface.
 */
export function instanceOfGetTotalStudents200Response(value: object): value is GetTotalStudents200Response {
    return true;
}

export function GetTotalStudents200ResponseFromJSON(json: any): GetTotalStudents200Response {
    return GetTotalStudents200ResponseFromJSONTyped(json, false);
}

export function GetTotalStudents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTotalStudents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : StatCardResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetTotalStudents200ResponseToJSON(json: any): GetTotalStudents200Response {
    return GetTotalStudents200ResponseToJSONTyped(json, false);
}

export function GetTotalStudents200ResponseToJSONTyped(value?: GetTotalStudents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StatCardResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

