/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Logout200ResponseData } from './Logout200ResponseData';
import {
    Logout200ResponseDataFromJSON,
    Logout200ResponseDataFromJSONTyped,
    Logout200ResponseDataToJSON,
    Logout200ResponseDataToJSONTyped,
} from './Logout200ResponseData';

/**
 * 
 * @export
 * @interface Logout200Response
 */
export interface Logout200Response {
    /**
     * 
     * @type {Logout200ResponseData}
     * @memberof Logout200Response
     */
    data?: Logout200ResponseData;
    /**
     * 
     * @type {boolean}
     * @memberof Logout200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Logout200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Logout200Response interface.
 */
export function instanceOfLogout200Response(value: object): value is Logout200Response {
    return true;
}

export function Logout200ResponseFromJSON(json: any): Logout200Response {
    return Logout200ResponseFromJSONTyped(json, false);
}

export function Logout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : Logout200ResponseDataFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Logout200ResponseToJSON(json: any): Logout200Response {
    return Logout200ResponseToJSONTyped(json, false);
}

export function Logout200ResponseToJSONTyped(value?: Logout200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Logout200ResponseDataToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

