/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout200ResponseData
 */
export interface Logout200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof Logout200ResponseData
     */
    message?: string;
}

/**
 * Check if a given object implements the Logout200ResponseData interface.
 */
export function instanceOfLogout200ResponseData(value: object): value is Logout200ResponseData {
    return true;
}

export function Logout200ResponseDataFromJSON(json: any): Logout200ResponseData {
    return Logout200ResponseDataFromJSONTyped(json, false);
}

export function Logout200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Logout200ResponseDataToJSON(json: any): Logout200ResponseData {
    return Logout200ResponseDataToJSONTyped(json, false);
}

export function Logout200ResponseDataToJSONTyped(value?: Logout200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

