/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model487c61ce04a9619a56693f5b75e0e9ceRequest
 */
export interface Model487c61ce04a9619a56693f5b75e0e9ceRequest {
    /**
     * 
     * @type {Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum}
     * @memberof Model487c61ce04a9619a56693f5b75e0e9ceRequest
     */
    status: Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Model487c61ce04a9619a56693f5b75e0e9ceRequest
     */
    adminNotes?: string | null;
}


/**
 * @export
 */
export const Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum = {
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;
export type Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum = typeof Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum[keyof typeof Model487c61ce04a9619a56693f5b75e0e9ceRequestStatusEnum];


/**
 * Check if a given object implements the Model487c61ce04a9619a56693f5b75e0e9ceRequest interface.
 */
export function instanceOfModel487c61ce04a9619a56693f5b75e0e9ceRequest(value: object): value is Model487c61ce04a9619a56693f5b75e0e9ceRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function Model487c61ce04a9619a56693f5b75e0e9ceRequestFromJSON(json: any): Model487c61ce04a9619a56693f5b75e0e9ceRequest {
    return Model487c61ce04a9619a56693f5b75e0e9ceRequestFromJSONTyped(json, false);
}

export function Model487c61ce04a9619a56693f5b75e0e9ceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model487c61ce04a9619a56693f5b75e0e9ceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'adminNotes': json['admin_notes'] == null ? undefined : json['admin_notes'],
    };
}

export function Model487c61ce04a9619a56693f5b75e0e9ceRequestToJSON(json: any): Model487c61ce04a9619a56693f5b75e0e9ceRequest {
    return Model487c61ce04a9619a56693f5b75e0e9ceRequestToJSONTyped(json, false);
}

export function Model487c61ce04a9619a56693f5b75e0e9ceRequestToJSONTyped(value?: Model487c61ce04a9619a56693f5b75e0e9ceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'admin_notes': value['adminNotes'],
    };
}

