/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model573de1fed352c1205a32c4d1b9877375Request
 */
export interface Model573de1fed352c1205a32c4d1b9877375Request {
    /**
     * 
     * @type {string}
     * @memberof Model573de1fed352c1205a32c4d1b9877375Request
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Model573de1fed352c1205a32c4d1b9877375Request
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof Model573de1fed352c1205a32c4d1b9877375Request
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Model573de1fed352c1205a32c4d1b9877375Request
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof Model573de1fed352c1205a32c4d1b9877375Request
     */
    passwordConfirmation?: string;
}

/**
 * Check if a given object implements the Model573de1fed352c1205a32c4d1b9877375Request interface.
 */
export function instanceOfModel573de1fed352c1205a32c4d1b9877375Request(value: object): value is Model573de1fed352c1205a32c4d1b9877375Request {
    return true;
}

export function Model573de1fed352c1205a32c4d1b9877375RequestFromJSON(json: any): Model573de1fed352c1205a32c4d1b9877375Request {
    return Model573de1fed352c1205a32c4d1b9877375RequestFromJSONTyped(json, false);
}

export function Model573de1fed352c1205a32c4d1b9877375RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model573de1fed352c1205a32c4d1b9877375Request {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'passwordConfirmation': json['password_confirmation'] == null ? undefined : json['password_confirmation'],
    };
}

export function Model573de1fed352c1205a32c4d1b9877375RequestToJSON(json: any): Model573de1fed352c1205a32c4d1b9877375Request {
    return Model573de1fed352c1205a32c4d1b9877375RequestToJSONTyped(json, false);
}

export function Model573de1fed352c1205a32c4d1b9877375RequestToJSONTyped(value?: Model573de1fed352c1205a32c4d1b9877375Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'password': value['password'],
        'password_confirmation': value['passwordConfirmation'],
    };
}

