/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface Model42f77e072dec84b0e1094cca1228298e200Response
 */
export interface Model42f77e072dec84b0e1094cca1228298e200Response {
    /**
     * 
     * @type {LoginResponse}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200Response
     */
    data?: LoginResponse;
    /**
     * 
     * @type {boolean}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Model42f77e072dec84b0e1094cca1228298e200Response interface.
 */
export function instanceOfModel42f77e072dec84b0e1094cca1228298e200Response(value: object): value is Model42f77e072dec84b0e1094cca1228298e200Response {
    return true;
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseFromJSON(json: any): Model42f77e072dec84b0e1094cca1228298e200Response {
    return Model42f77e072dec84b0e1094cca1228298e200ResponseFromJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model42f77e072dec84b0e1094cca1228298e200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseToJSON(json: any): Model42f77e072dec84b0e1094cca1228298e200Response {
    return Model42f77e072dec84b0e1094cca1228298e200ResponseToJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseToJSONTyped(value?: Model42f77e072dec84b0e1094cca1228298e200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LoginResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

