/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model42f77e072dec84b0e1094cca1228298e200ResponseUser
 */
export interface Model42f77e072dec84b0e1094cca1228298e200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200ResponseUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200ResponseUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200ResponseUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200ResponseUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298e200ResponseUser
     */
    role?: string;
}

/**
 * Check if a given object implements the Model42f77e072dec84b0e1094cca1228298e200ResponseUser interface.
 */
export function instanceOfModel42f77e072dec84b0e1094cca1228298e200ResponseUser(value: object): value is Model42f77e072dec84b0e1094cca1228298e200ResponseUser {
    return true;
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseUserFromJSON(json: any): Model42f77e072dec84b0e1094cca1228298e200ResponseUser {
    return Model42f77e072dec84b0e1094cca1228298e200ResponseUserFromJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model42f77e072dec84b0e1094cca1228298e200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseUserToJSON(json: any): Model42f77e072dec84b0e1094cca1228298e200ResponseUser {
    return Model42f77e072dec84b0e1094cca1228298e200ResponseUserToJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298e200ResponseUserToJSONTyped(value?: Model42f77e072dec84b0e1094cca1228298e200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'role': value['role'],
    };
}

