/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData } from './Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData';
import {
    Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSON,
    Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSONTyped,
    Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSON,
    Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSONTyped,
} from './Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData';

/**
 * 
 * @export
 * @interface Model03afb12b342c2ea43bdc1de4f39e91a8200Response
 */
export interface Model03afb12b342c2ea43bdc1de4f39e91a8200Response {
    /**
     * 
     * @type {Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData}
     * @memberof Model03afb12b342c2ea43bdc1de4f39e91a8200Response
     */
    data?: Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData;
    /**
     * 
     * @type {boolean}
     * @memberof Model03afb12b342c2ea43bdc1de4f39e91a8200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model03afb12b342c2ea43bdc1de4f39e91a8200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Model03afb12b342c2ea43bdc1de4f39e91a8200Response interface.
 */
export function instanceOfModel03afb12b342c2ea43bdc1de4f39e91a8200Response(value: object): value is Model03afb12b342c2ea43bdc1de4f39e91a8200Response {
    return true;
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseFromJSON(json: any): Model03afb12b342c2ea43bdc1de4f39e91a8200Response {
    return Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseFromJSONTyped(json, false);
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model03afb12b342c2ea43bdc1de4f39e91a8200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseToJSON(json: any): Model03afb12b342c2ea43bdc1de4f39e91a8200Response {
    return Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseToJSONTyped(json, false);
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseToJSONTyped(value?: Model03afb12b342c2ea43bdc1de4f39e91a8200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

