/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';

/**
 * 
 * @export
 * @interface Model826dc6b24dd704607aa018a59207dd96200Response
 */
export interface Model826dc6b24dd704607aa018a59207dd96200Response {
    /**
     * 
     * @type {Array<Payment>}
     * @memberof Model826dc6b24dd704607aa018a59207dd96200Response
     */
    data?: Array<Payment>;
    /**
     * 
     * @type {boolean}
     * @memberof Model826dc6b24dd704607aa018a59207dd96200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model826dc6b24dd704607aa018a59207dd96200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Model826dc6b24dd704607aa018a59207dd96200Response interface.
 */
export function instanceOfModel826dc6b24dd704607aa018a59207dd96200Response(value: object): value is Model826dc6b24dd704607aa018a59207dd96200Response {
    return true;
}

export function Model826dc6b24dd704607aa018a59207dd96200ResponseFromJSON(json: any): Model826dc6b24dd704607aa018a59207dd96200Response {
    return Model826dc6b24dd704607aa018a59207dd96200ResponseFromJSONTyped(json, false);
}

export function Model826dc6b24dd704607aa018a59207dd96200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model826dc6b24dd704607aa018a59207dd96200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PaymentFromJSON)),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Model826dc6b24dd704607aa018a59207dd96200ResponseToJSON(json: any): Model826dc6b24dd704607aa018a59207dd96200Response {
    return Model826dc6b24dd704607aa018a59207dd96200ResponseToJSONTyped(json, false);
}

export function Model826dc6b24dd704607aa018a59207dd96200ResponseToJSONTyped(value?: Model826dc6b24dd704607aa018a59207dd96200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PaymentToJSON)),
        'didError': value['didError'],
        'error': value['error'],
    };
}

