/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model42f77e072dec84b0e1094cca1228298eRequest
 */
export interface Model42f77e072dec84b0e1094cca1228298eRequest {
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298eRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Model42f77e072dec84b0e1094cca1228298eRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the Model42f77e072dec84b0e1094cca1228298eRequest interface.
 */
export function instanceOfModel42f77e072dec84b0e1094cca1228298eRequest(value: object): value is Model42f77e072dec84b0e1094cca1228298eRequest {
    return true;
}

export function Model42f77e072dec84b0e1094cca1228298eRequestFromJSON(json: any): Model42f77e072dec84b0e1094cca1228298eRequest {
    return Model42f77e072dec84b0e1094cca1228298eRequestFromJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298eRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model42f77e072dec84b0e1094cca1228298eRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function Model42f77e072dec84b0e1094cca1228298eRequestToJSON(json: any): Model42f77e072dec84b0e1094cca1228298eRequest {
    return Model42f77e072dec84b0e1094cca1228298eRequestToJSONTyped(json, false);
}

export function Model42f77e072dec84b0e1094cca1228298eRequestToJSONTyped(value?: Model42f77e072dec84b0e1094cca1228298eRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

