/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData
 */
export interface Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData
     */
    message?: string;
}

/**
 * Check if a given object implements the Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData interface.
 */
export function instanceOfModel0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData(value: object): value is Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData {
    return true;
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSON(json: any): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData {
    return Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSONTyped(json, false);
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSON(json: any): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData {
    return Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSONTyped(json, false);
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSONTyped(value?: Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

