/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData } from './Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData';
import {
    Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSON,
    Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSONTyped,
    Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSON,
    Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSONTyped,
} from './Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData';

/**
 * 
 * @export
 * @interface Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response
 */
export interface Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response {
    /**
     * 
     * @type {Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData}
     * @memberof Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response
     */
    data?: Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseData;
    /**
     * 
     * @type {boolean}
     * @memberof Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response interface.
 */
export function instanceOfModel0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response(value: object): value is Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response {
    return true;
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseFromJSON(json: any): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response {
    return Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseFromJSONTyped(json, false);
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseToJSON(json: any): Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response {
    return Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseToJSONTyped(json, false);
}

export function Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseToJSONTyped(value?: Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Model0ab4e3cf7bc4f7ec81b48f7928c7de7c200ResponseDataToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

