/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData
 */
export interface Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData
     */
    message?: string;
}

/**
 * Check if a given object implements the Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData interface.
 */
export function instanceOfModel03afb12b342c2ea43bdc1de4f39e91a8200ResponseData(value: object): value is Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData {
    return true;
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSON(json: any): Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData {
    return Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSONTyped(json, false);
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSON(json: any): Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData {
    return Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSONTyped(json, false);
}

export function Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseDataToJSONTyped(value?: Model03afb12b342c2ea43bdc1de4f39e91a8200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

