/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorePaymentResponse } from './StorePaymentResponse';
import {
    StorePaymentResponseFromJSON,
    StorePaymentResponseFromJSONTyped,
    StorePaymentResponseToJSON,
    StorePaymentResponseToJSONTyped,
} from './StorePaymentResponse';

/**
 * 
 * @export
 * @interface Model5e2794ba3d3c64e70873367505e4a751201Response
 */
export interface Model5e2794ba3d3c64e70873367505e4a751201Response {
    /**
     * 
     * @type {StorePaymentResponse}
     * @memberof Model5e2794ba3d3c64e70873367505e4a751201Response
     */
    data?: StorePaymentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof Model5e2794ba3d3c64e70873367505e4a751201Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model5e2794ba3d3c64e70873367505e4a751201Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Model5e2794ba3d3c64e70873367505e4a751201Response interface.
 */
export function instanceOfModel5e2794ba3d3c64e70873367505e4a751201Response(value: object): value is Model5e2794ba3d3c64e70873367505e4a751201Response {
    return true;
}

export function Model5e2794ba3d3c64e70873367505e4a751201ResponseFromJSON(json: any): Model5e2794ba3d3c64e70873367505e4a751201Response {
    return Model5e2794ba3d3c64e70873367505e4a751201ResponseFromJSONTyped(json, false);
}

export function Model5e2794ba3d3c64e70873367505e4a751201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model5e2794ba3d3c64e70873367505e4a751201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : StorePaymentResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Model5e2794ba3d3c64e70873367505e4a751201ResponseToJSON(json: any): Model5e2794ba3d3c64e70873367505e4a751201Response {
    return Model5e2794ba3d3c64e70873367505e4a751201ResponseToJSONTyped(json, false);
}

export function Model5e2794ba3d3c64e70873367505e4a751201ResponseToJSONTyped(value?: Model5e2794ba3d3c64e70873367505e4a751201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StorePaymentResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

