/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Receipt } from './Receipt';
import {
    ReceiptFromJSON,
    ReceiptFromJSONTyped,
    ReceiptToJSON,
    ReceiptToJSONTyped,
} from './Receipt';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    studentId?: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    amount?: string;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    paymentDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    paymentMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    referenceNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    receiptPath?: string | null;
    /**
     * 
     * @type {PaymentStatusEnum}
     * @memberof Payment
     */
    status?: PaymentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    adminNotes?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Student}
     * @memberof Payment
     */
    student?: Student;
    /**
     * 
     * @type {User}
     * @memberof Payment
     */
    user?: User;
    /**
     * 
     * @type {Receipt}
     * @memberof Payment
     */
    receipt?: Receipt | null;
}


/**
 * @export
 */
export const PaymentStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;
export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'studentId': json['student_id'] == null ? undefined : json['student_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'paymentDate': json['payment_date'] == null ? undefined : (new Date(json['payment_date'])),
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'referenceNumber': json['reference_number'] == null ? undefined : json['reference_number'],
        'receiptPath': json['receipt_path'] == null ? undefined : json['receipt_path'],
        'status': json['status'] == null ? undefined : json['status'],
        'adminNotes': json['admin_notes'] == null ? undefined : json['admin_notes'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'student': json['student'] == null ? undefined : StudentFromJSON(json['student']),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'receipt': json['receipt'] == null ? undefined : ReceiptFromJSON(json['receipt']),
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'student_id': value['studentId'],
        'user_id': value['userId'],
        'amount': value['amount'],
        'payment_date': value['paymentDate'] == null ? value['paymentDate'] : value['paymentDate'].toISOString().substring(0,10),
        'payment_method': value['paymentMethod'],
        'reference_number': value['referenceNumber'],
        'receipt_path': value['receiptPath'],
        'status': value['status'],
        'admin_notes': value['adminNotes'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'student': StudentToJSON(value['student']),
        'user': UserToJSON(value['user']),
        'receipt': ReceiptToJSON(value['receipt']),
    };
}

