/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Rank
 */
export interface Rank {
    /**
     * 
     * @type {number}
     * @memberof Rank
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Rank
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Rank
     */
    colorCode?: string;
    /**
     * 
     * @type {RankTypeEnum}
     * @memberof Rank
     */
    type?: RankTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Rank
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof Rank
     */
    sortOrder?: number;
    /**
     * 
     * @type {number}
     * @memberof Rank
     */
    requirementMonths?: number;
    /**
     * 
     * @type {Date}
     * @memberof Rank
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Rank
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const RankTypeEnum = {
    Kyu: 'KYU',
    Dan: 'DAN'
} as const;
export type RankTypeEnum = typeof RankTypeEnum[keyof typeof RankTypeEnum];


/**
 * Check if a given object implements the Rank interface.
 */
export function instanceOfRank(value: object): value is Rank {
    return true;
}

export function RankFromJSON(json: any): Rank {
    return RankFromJSONTyped(json, false);
}

export function RankFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rank {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'colorCode': json['color_code'] == null ? undefined : json['color_code'],
        'type': json['type'] == null ? undefined : json['type'],
        'number': json['number'] == null ? undefined : json['number'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'requirementMonths': json['requirement_months'] == null ? undefined : json['requirement_months'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function RankToJSON(json: any): Rank {
    return RankToJSONTyped(json, false);
}

export function RankToJSONTyped(value?: Rank | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color_code': value['colorCode'],
        'type': value['type'],
        'number': value['number'],
        'sort_order': value['sortOrder'],
        'requirement_months': value['requirementMonths'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

