/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Receipt
 */
export interface Receipt {
    /**
     * 
     * @type {number}
     * @memberof Receipt
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Receipt
     */
    paymentId?: number;
    /**
     * 
     * @type {string}
     * @memberof Receipt
     */
    receiptNumber?: string;
    /**
     * 
     * @type {Date}
     * @memberof Receipt
     */
    issuedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Receipt
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Receipt
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Receipt interface.
 */
export function instanceOfReceipt(value: object): value is Receipt {
    return true;
}

export function ReceiptFromJSON(json: any): Receipt {
    return ReceiptFromJSONTyped(json, false);
}

export function ReceiptFromJSONTyped(json: any, ignoreDiscriminator: boolean): Receipt {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paymentId': json['payment_id'] == null ? undefined : json['payment_id'],
        'receiptNumber': json['receipt_number'] == null ? undefined : json['receipt_number'],
        'issuedAt': json['issued_at'] == null ? undefined : (new Date(json['issued_at'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ReceiptToJSON(json: any): Receipt {
    return ReceiptToJSONTyped(json, false);
}

export function ReceiptToJSONTyped(value?: Receipt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payment_id': value['paymentId'],
        'receipt_number': value['receiptNumber'],
        'issued_at': value['issuedAt'] == null ? value['issuedAt'] : value['issuedAt'].toISOString(),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

