/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterResponse } from './RegisterResponse';
import {
    RegisterResponseFromJSON,
    RegisterResponseFromJSONTyped,
    RegisterResponseToJSON,
    RegisterResponseToJSONTyped,
} from './RegisterResponse';

/**
 * 
 * @export
 * @interface Register201Response
 */
export interface Register201Response {
    /**
     * 
     * @type {RegisterResponse}
     * @memberof Register201Response
     */
    data?: RegisterResponse;
    /**
     * 
     * @type {boolean}
     * @memberof Register201Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Register201Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the Register201Response interface.
 */
export function instanceOfRegister201Response(value: object): value is Register201Response {
    return true;
}

export function Register201ResponseFromJSON(json: any): Register201Response {
    return Register201ResponseFromJSONTyped(json, false);
}

export function Register201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : RegisterResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Register201ResponseToJSON(json: any): Register201Response {
    return Register201ResponseToJSONTyped(json, false);
}

export function Register201ResponseToJSONTyped(value?: Register201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RegisterResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

