/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface ShowStudent200Response
 */
export interface ShowStudent200Response {
    /**
     * 
     * @type {Student}
     * @memberof ShowStudent200Response
     */
    data?: Student;
    /**
     * 
     * @type {boolean}
     * @memberof ShowStudent200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShowStudent200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ShowStudent200Response interface.
 */
export function instanceOfShowStudent200Response(value: object): value is ShowStudent200Response {
    return true;
}

export function ShowStudent200ResponseFromJSON(json: any): ShowStudent200Response {
    return ShowStudent200ResponseFromJSONTyped(json, false);
}

export function ShowStudent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowStudent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : StudentFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ShowStudent200ResponseToJSON(json: any): ShowStudent200Response {
    return ShowStudent200ResponseToJSONTyped(json, false);
}

export function ShowStudent200ResponseToJSONTyped(value?: ShowStudent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': StudentToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

