/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';

/**
 * 
 * @export
 * @interface ShowPayment200Response
 */
export interface ShowPayment200Response {
    /**
     * 
     * @type {Payment}
     * @memberof ShowPayment200Response
     */
    data?: Payment;
    /**
     * 
     * @type {boolean}
     * @memberof ShowPayment200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShowPayment200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ShowPayment200Response interface.
 */
export function instanceOfShowPayment200Response(value: object): value is ShowPayment200Response {
    return true;
}

export function ShowPayment200ResponseFromJSON(json: any): ShowPayment200Response {
    return ShowPayment200ResponseFromJSONTyped(json, false);
}

export function ShowPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowPayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PaymentFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ShowPayment200ResponseToJSON(json: any): ShowPayment200Response {
    return ShowPayment200ResponseToJSONTyped(json, false);
}

export function ShowPayment200ResponseToJSONTyped(value?: ShowPayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaymentToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

