/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatCardResponseTrend
 */
export interface StatCardResponseTrend {
    /**
     * 
     * @type {number}
     * @memberof StatCardResponseTrend
     */
    value?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StatCardResponseTrend
     */
    isPositive?: boolean;
}

/**
 * Check if a given object implements the StatCardResponseTrend interface.
 */
export function instanceOfStatCardResponseTrend(value: object): value is StatCardResponseTrend {
    return true;
}

export function StatCardResponseTrendFromJSON(json: any): StatCardResponseTrend {
    return StatCardResponseTrendFromJSONTyped(json, false);
}

export function StatCardResponseTrendFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatCardResponseTrend {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'isPositive': json['isPositive'] == null ? undefined : json['isPositive'],
    };
}

export function StatCardResponseTrendToJSON(json: any): StatCardResponseTrend {
    return StatCardResponseTrendToJSONTyped(json, false);
}

export function StatCardResponseTrendToJSONTyped(value?: StatCardResponseTrend | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'isPositive': value['isPositive'],
    };
}

