/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoreRepresentativeRequestStudent } from './StoreRepresentativeRequestStudent';
import {
    StoreRepresentativeRequestStudentFromJSON,
    StoreRepresentativeRequestStudentFromJSONTyped,
    StoreRepresentativeRequestStudentToJSON,
    StoreRepresentativeRequestStudentToJSONTyped,
} from './StoreRepresentativeRequestStudent';

/**
 * 
 * @export
 * @interface StoreRepresentativeRequest
 */
export interface StoreRepresentativeRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequest
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof StoreRepresentativeRequest
     */
    dob: Date;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequest
     */
    password?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StoreRepresentativeRequest
     */
    createStudent?: boolean;
    /**
     * 
     * @type {StoreRepresentativeRequestStudent}
     * @memberof StoreRepresentativeRequest
     */
    student?: StoreRepresentativeRequestStudent;
}

/**
 * Check if a given object implements the StoreRepresentativeRequest interface.
 */
export function instanceOfStoreRepresentativeRequest(value: object): value is StoreRepresentativeRequest {
    if ((!('firstName' in value) && !('first_name' in value)) || (value['firstName'] === undefined && value['first_name'] === undefined)) return false;
    if ((!('lastName' in value) && !('last_name' in value)) || (value['lastName'] === undefined && value['last_name'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('dob' in value) || value['dob'] === undefined) return false;
    return true;
}

export function StoreRepresentativeRequestFromJSON(json: any): StoreRepresentativeRequest {
    return StoreRepresentativeRequestFromJSONTyped(json, false);
}

export function StoreRepresentativeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreRepresentativeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'dob': (new Date(json['dob'])),
        'phone': json['phone'] == null ? undefined : json['phone'],
        'password': json['password'] == null ? undefined : json['password'],
        'createStudent': json['create_student'] == null ? undefined : json['create_student'],
        'student': json['student'] == null ? undefined : StoreRepresentativeRequestStudentFromJSON(json['student']),
    };
}

export function StoreRepresentativeRequestToJSON(json: any): StoreRepresentativeRequest {
    return StoreRepresentativeRequestToJSONTyped(json, false);
}

export function StoreRepresentativeRequestToJSONTyped(value?: StoreRepresentativeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'dob': value['dob'].toISOString().substring(0,10),
        'phone': value['phone'],
        'password': value['password'],
        'create_student': value['createStudent'],
        'student': StoreRepresentativeRequestStudentToJSON(value['student']),
    };
}

