/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';

/**
 * 
 * @export
 * @interface StorePaymentResponse
 */
export interface StorePaymentResponse {
    /**
     * 
     * @type {string}
     * @memberof StorePaymentResponse
     */
    message?: string;
    /**
     * 
     * @type {Payment}
     * @memberof StorePaymentResponse
     */
    payment?: Payment;
}

/**
 * Check if a given object implements the StorePaymentResponse interface.
 */
export function instanceOfStorePaymentResponse(value: object): value is StorePaymentResponse {
    return true;
}

export function StorePaymentResponseFromJSON(json: any): StorePaymentResponse {
    return StorePaymentResponseFromJSONTyped(json, false);
}

export function StorePaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorePaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'payment': json['payment'] == null ? undefined : PaymentFromJSON(json['payment']),
    };
}

export function StorePaymentResponseToJSON(json: any): StorePaymentResponse {
    return StorePaymentResponseToJSONTyped(json, false);
}

export function StorePaymentResponseToJSONTyped(value?: StorePaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'payment': PaymentToJSON(value['payment']),
    };
}

