/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreRepresentativeRequestStudent
 */
export interface StoreRepresentativeRequestStudent {
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequestStudent
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequestStudent
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof StoreRepresentativeRequestStudent
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequestStudent
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequestStudent
     */
    email?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRepresentativeRequestStudent
     */
    rankId?: number;
    /**
     * 
     * @type {number}
     * @memberof StoreRepresentativeRequestStudent
     */
    discountPolicyId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof StoreRepresentativeRequestStudent
     */
    enrollmentDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StoreRepresentativeRequestStudent
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the StoreRepresentativeRequestStudent interface.
 */
export function instanceOfStoreRepresentativeRequestStudent(value: object): value is StoreRepresentativeRequestStudent {
    return true;
}

export function StoreRepresentativeRequestStudentFromJSON(json: any): StoreRepresentativeRequestStudent {
    return StoreRepresentativeRequestStudentFromJSONTyped(json, false);
}

export function StoreRepresentativeRequestStudentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreRepresentativeRequestStudent {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'dob': json['dob'] == null ? undefined : (new Date(json['dob'])),
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'rankId': json['rank_id'] == null ? undefined : json['rank_id'],
        'discountPolicyId': json['discount_policy_id'] == null ? undefined : json['discount_policy_id'],
        'enrollmentDate': json['enrollment_date'] == null ? undefined : (new Date(json['enrollment_date'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function StoreRepresentativeRequestStudentToJSON(json: any): StoreRepresentativeRequestStudent {
    return StoreRepresentativeRequestStudentToJSONTyped(json, false);
}

export function StoreRepresentativeRequestStudentToJSONTyped(value?: StoreRepresentativeRequestStudent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'dob': value['dob'] == null ? value['dob'] : value['dob'].toISOString().substring(0,10),
        'phone': value['phone'],
        'email': value['email'],
        'rank_id': value['rankId'],
        'discount_policy_id': value['discountPolicyId'],
        'enrollment_date': value['enrollmentDate'] == null ? value['enrollmentDate'] : value['enrollmentDate'].toISOString().substring(0,10),
        'notes': value['notes'],
    };
}

