/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { DiscountPolicy } from './DiscountPolicy';
import {
    DiscountPolicyFromJSON,
    DiscountPolicyFromJSONTyped,
    DiscountPolicyToJSON,
    DiscountPolicyToJSONTyped,
} from './DiscountPolicy';
import type { Rank } from './Rank';
import {
    RankFromJSON,
    RankFromJSONTyped,
    RankToJSON,
    RankToJSONTyped,
} from './Rank';

/**
 * 
 * @export
 * @interface Student
 */
export interface Student {
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    rankId?: number;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    discountPolicyId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    representativeId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Student
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Student
     */
    lastPromotionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Student
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Student
     */
    updatedAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof Student
     */
    user?: User;
    /**
     * 
     * @type {Rank}
     * @memberof Student
     */
    rank?: Rank;
    /**
     * 
     * @type {DiscountPolicy}
     * @memberof Student
     */
    discountPolicy?: DiscountPolicy | null;
}

/**
 * Check if a given object implements the Student interface.
 */
export function instanceOfStudent(value: object): value is Student {
    return true;
}

export function StudentFromJSON(json: any): Student {
    return StudentFromJSONTyped(json, false);
}

export function StudentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Student {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'rankId': json['rank_id'] == null ? undefined : json['rank_id'],
        'discountPolicyId': json['discount_policy_id'] == null ? undefined : json['discount_policy_id'],
        'representativeId': json['representative_id'] == null ? undefined : json['representative_id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'lastPromotionDate': json['last_promotion_date'] == null ? undefined : (new Date(json['last_promotion_date'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'rank': json['rank'] == null ? undefined : RankFromJSON(json['rank']),
        'discountPolicy': json['discount_policy'] == null ? undefined : DiscountPolicyFromJSON(json['discount_policy']),
    };
}

export function StudentToJSON(json: any): Student {
    return StudentToJSONTyped(json, false);
}

export function StudentToJSONTyped(value?: Student | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'rank_id': value['rankId'],
        'discount_policy_id': value['discountPolicyId'],
        'representative_id': value['representativeId'],
        'is_active': value['isActive'],
        'last_promotion_date': value['lastPromotionDate'] == null ? value['lastPromotionDate'] : value['lastPromotionDate'].toISOString().substring(0,10),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'user': UserToJSON(value['user']),
        'rank': RankToJSON(value['rank']),
        'discount_policy': DiscountPolicyToJSON(value['discountPolicy']),
    };
}

