/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyPaymentResponse } from './VerifyPaymentResponse';
import {
    VerifyPaymentResponseFromJSON,
    VerifyPaymentResponseFromJSONTyped,
    VerifyPaymentResponseToJSON,
    VerifyPaymentResponseToJSONTyped,
} from './VerifyPaymentResponse';

/**
 * 
 * @export
 * @interface VerifyPayment200Response
 */
export interface VerifyPayment200Response {
    /**
     * 
     * @type {VerifyPaymentResponse}
     * @memberof VerifyPayment200Response
     */
    data?: VerifyPaymentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof VerifyPayment200Response
     */
    didError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VerifyPayment200Response
     */
    error?: string | null;
}

/**
 * Check if a given object implements the VerifyPayment200Response interface.
 */
export function instanceOfVerifyPayment200Response(value: object): value is VerifyPayment200Response {
    return true;
}

export function VerifyPayment200ResponseFromJSON(json: any): VerifyPayment200Response {
    return VerifyPayment200ResponseFromJSONTyped(json, false);
}

export function VerifyPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : VerifyPaymentResponseFromJSON(json['data']),
        'didError': json['didError'] == null ? undefined : json['didError'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function VerifyPayment200ResponseToJSON(json: any): VerifyPayment200Response {
    return VerifyPayment200ResponseToJSONTyped(json, false);
}

export function VerifyPayment200ResponseToJSONTyped(value?: VerifyPayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': VerifyPaymentResponseToJSON(value['data']),
        'didError': value['didError'],
        'error': value['error'],
    };
}

