/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';

/**
 * 
 * @export
 * @interface VerifyPaymentResponse
 */
export interface VerifyPaymentResponse {
    /**
     * 
     * @type {string}
     * @memberof VerifyPaymentResponse
     */
    message?: string;
    /**
     * 
     * @type {Payment}
     * @memberof VerifyPaymentResponse
     */
    payment?: Payment;
}

/**
 * Check if a given object implements the VerifyPaymentResponse interface.
 */
export function instanceOfVerifyPaymentResponse(value: object): value is VerifyPaymentResponse {
    return true;
}

export function VerifyPaymentResponseFromJSON(json: any): VerifyPaymentResponse {
    return VerifyPaymentResponseFromJSONTyped(json, false);
}

export function VerifyPaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'payment': json['payment'] == null ? undefined : PaymentFromJSON(json['payment']),
    };
}

export function VerifyPaymentResponseToJSON(json: any): VerifyPaymentResponse {
    return VerifyPaymentResponseToJSONTyped(json, false);
}

export function VerifyPaymentResponseToJSONTyped(value?: VerifyPaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'payment': PaymentToJSON(value['payment']),
    };
}

