/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyPaymentRequest
 */
export interface VerifyPaymentRequest {
    /**
     * 
     * @type {VerifyPaymentRequestStatusEnum}
     * @memberof VerifyPaymentRequest
     */
    status: VerifyPaymentRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof VerifyPaymentRequest
     */
    adminNotes?: string | null;
}


/**
 * @export
 */
export const VerifyPaymentRequestStatusEnum = {
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;
export type VerifyPaymentRequestStatusEnum = typeof VerifyPaymentRequestStatusEnum[keyof typeof VerifyPaymentRequestStatusEnum];


/**
 * Check if a given object implements the VerifyPaymentRequest interface.
 */
export function instanceOfVerifyPaymentRequest(value: object): value is VerifyPaymentRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VerifyPaymentRequestFromJSON(json: any): VerifyPaymentRequest {
    return VerifyPaymentRequestFromJSONTyped(json, false);
}

export function VerifyPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'adminNotes': json['admin_notes'] == null ? undefined : json['admin_notes'],
    };
}

export function VerifyPaymentRequestToJSON(json: any): VerifyPaymentRequest {
    return VerifyPaymentRequestToJSONTyped(json, false);
}

export function VerifyPaymentRequestToJSONTyped(value?: VerifyPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'admin_notes': value['adminNotes'],
    };
}

