import { Configuration } from '../api-client/runtime';
import { AutenticacinApi } from '../api-client/apis/AutenticacinApi';
import { AdministracinAlumnosApi } from '../api-client/apis/AdministracinAlumnosApi';
import { AdministracinRepresentantesApi } from '../api-client/apis/AdministracinRepresentantesApi';
import { AdministracinEstadsticasApi } from '../api-client/apis/AdministracinEstadsticasApi';
import { useAuthStore } from '../store/useAuthStore';
import Toastify from 'toastify-js';
import 'toastify-js/src/toastify.css';

// Base Configuration for the generated API clients
export const apiConfig = new Configuration({
  basePath: import.meta.env.VITE_API_URL || 'http://localhost:8000',
  accessToken: async () => {
    const token = useAuthStore.getState().token;
    return token || '';
  }
});

/**
 * Helper to instantiate any API client class with the global configuration
 */
export function getApiClient<T>(ApiClass: new (config: Configuration) => T): T {
  return new ApiClass(apiConfig);
}

/**
 * Custom wrapper for API client promises to catch network/response errors,
 * handle authentication expiration, and show user-friendly notifications.
 */
export async function apiWrapper<T>(promise: Promise<T>): Promise<T> {
  try {
    return await promise;
  } catch (error: any) {
    console.error('API Error:', error);

    // Intercept API errors generated by runtime.ts
    if (error && error.name === 'ResponseError') {
      const response = error.response as Response;
      const status = response.status;

      // Handle 401 Unauthorized
      if (status === 401) {
        useAuthStore.getState().logout();
        
        Toastify({
          text: "Su sesión ha expirado. Por favor, inicie sesión de nuevo.",
          duration: 4000,
          gravity: "top",
          position: "right",
          style: {
            background: "linear-gradient(to right, #ff5f6d, #ffc371)",
          }
        }).showToast();

        throw error;
      }

      // Try to parse server validation/error message
      let errorMessage = `Error del servidor (${status}). Por favor, intente de nuevo.`;
      try {
        const body = await response.json();
        if (body && body.message) {
          errorMessage = body.message;
        } else if (body && body.error) {
          errorMessage = body.error;
        } else if (body && body.errors) {
          // If Laravel validation errors are present
          const validationErrors = Object.values(body.errors).flat().join(', ');
          if (validationErrors) {
            errorMessage = validationErrors;
          }
        }
      } catch (_) {
        // Fallback to reading text if JSON parsing fails
        try {
          const text = await response.text();
          if (text && text.length < 150) {
            errorMessage = text;
          }
        } catch (_) {}
      }

      Toastify({
        text: errorMessage,
        duration: 4000,
        gravity: "top",
        position: "right",
        style: {
          background: "linear-gradient(to right, #e53935, #e35d5b)",
        }
      }).showToast();
    } else if (error && error.name === 'FetchError') {
      // Handle physical connection/DNS failure
      Toastify({
        text: "Error de conexión. Asegúrese de que el servidor está en línea.",
        duration: 5000,
        gravity: "top",
        position: "right",
        style: {
          background: "linear-gradient(to right, #e53935, #e35d5b)",
        }
      }).showToast();
    } else {
      // General JavaScript exception or unexpected error
      Toastify({
        text: error?.message || "Ocurrió un error inesperado.",
        duration: 4000,
        gravity: "top",
        position: "right",
        style: {
          background: "linear-gradient(to right, #e53935, #e35d5b)",
        }
      }).showToast();
    }

    throw error;
  }
}

// -------------------------------------------------------------
// Preconfigured instances of raw APIs
// -------------------------------------------------------------
const rawAuthApi = new AutenticacinApi(apiConfig);
const rawAlumnosApi = new AdministracinAlumnosApi(apiConfig);
const rawRepresentantesApi = new AdministracinRepresentantesApi(apiConfig);
const rawStatsApi = new AdministracinEstadsticasApi(apiConfig);

// -------------------------------------------------------------
// Mapped clean wrappers for easy integration
// -------------------------------------------------------------

/**
 * Wrapper client for Autenticación routes.
 */
export const authApiClient = {
  /**
   * Log in a user.
   */
  login: (email: string, password = 'password') =>
    apiWrapper(
      rawAuthApi.login({
        loginRequest: { email, password }
      })
    ),

  /**
   * Log out current user session.
   */
  logout: () =>
    apiWrapper(rawAuthApi.logout()),

  /**
   * Register a new user/representative.
   */
  register: (payload: { firstName: string; lastName: string; email: string; password?: string; passwordConfirmation?: string }) => {
    const password = payload.password || 'password123';
    const passwordConfirmation = payload.passwordConfirmation || password;
    return apiWrapper(
      rawAuthApi.register({
        registerRequest: {
          firstName: payload.firstName,
          lastName: payload.lastName,
          email: payload.email,
          password,
          passwordConfirmation
        }
      })
    );
  }
};

/**
 * Wrapper client for Student Administration routes.
 * Maps raw hashed methods to human-readable names.
 */
export const adminStudentsApiClient = {
  /**
   * List all registered students (Admin only).
   */
  getAllStudents: () =>
    apiWrapper(rawAlumnosApi.getStudents()),

  /**
   * Register a new student (Admin only).
   */
  createStudent: (payload?: any) =>
    apiWrapper(rawAlumnosApi.enrollStudent(payload)),

  /**
   * Retrieve profile details for a specific student (Admin only).
   */
  getStudentDetail: (studentId: number) =>
    apiWrapper(rawAlumnosApi.showStudent({ student: studentId })),

  /**
   * Update student details (Admin only).
   */
  updateStudent: (studentId: number, payload?: any) =>
    apiWrapper(rawAlumnosApi.updateStudent({ student: studentId, ...payload })),

  /**
   * Suspends or restores a student's active status (Admin only).
   */
  updateStudentStatus: (studentId: number) =>
    apiWrapper(rawAlumnosApi.toggleStudentStatus({ student: studentId }))
};

/**
 * Wrapper client for User/Representative Administration routes.
 * Maps raw hashed methods to human-readable names.
 */
export const adminRepresentativesApiClient = {
  /**
   * List all registered representatives (Admin only).
   */
  getAllRepresentatives: () =>
    apiWrapper(rawRepresentantesApi.getRepresentatives()),

  /**
   * Retrieve representative details along with associated students (Admin only).
   */
  getRepresentativeDetail: (userId: number) =>
    apiWrapper(rawRepresentantesApi.showRepresentative({ user: userId })),

  /**
   * Suspends a representative account and all associated students in cascade (Admin only).
   */
  deactivateRepresentative: (userId: number) =>
    apiWrapper(rawRepresentantesApi.deactivateRepresentative({ user: userId }))
};

/**
 * Wrapper client for Administracion Estadisticas routes.
 */
export const adminStatsApiClient = {
  getTotalStudents: () =>
    apiWrapper(rawStatsApi.getTotalStudents()),

  getActiveStudents: () =>
    apiWrapper(rawStatsApi.getActiveStudents()),

  getInactiveStudents: () =>
    apiWrapper(rawStatsApi.getInactiveStudents())
};
