/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type StoreRepresentativeRequest,
    StoreRepresentativeRequestFromJSON,
    StoreRepresentativeRequestToJSON,
} from '../models/StoreRepresentativeRequest';

export interface AdministracinRepresentantesApiDeactivateRepresentativeRequest {
    user: number;
}

export interface AdministracinRepresentantesApiShowRepresentativeRequest {
    user: number;
}

export interface AdministracinRepresentantesApiStoreRepresentativeOperationRequest {
    storeRepresentativeRequest: StoreRepresentativeRequest;
}

/**
 * 
 */
export class AdministracinRepresentantesApi extends runtime.BaseAPI {

    /**
     * Creates request options for deactivateRepresentative without sending the request
     */
    async deactivateRepresentativeRequestOpts(requestParameters: AdministracinRepresentantesApiDeactivateRepresentativeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling deactivateRepresentative().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives/{user}/deactivate`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Suspende la cuenta de un representante y desactiva a todos sus alumnos asociados en cascada (Solo Admin).
     * Desactivar un representante y sus alumnos
     */
    async deactivateRepresentativeRaw(requestParameters: AdministracinRepresentantesApiDeactivateRepresentativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deactivateRepresentativeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Suspende la cuenta de un representante y desactiva a todos sus alumnos asociados en cascada (Solo Admin).
     * Desactivar un representante y sus alumnos
     */
    async deactivateRepresentative(requestParameters: AdministracinRepresentantesApiDeactivateRepresentativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deactivateRepresentativeRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getRepresentatives without sending the request
     */
    async getRepresentativesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene una lista de todos los usuarios registrados como representantes o adultos (Solo Admin).
     * Listar todos los representantes
     */
    async getRepresentativesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getRepresentativesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene una lista de todos los usuarios registrados como representantes o adultos (Solo Admin).
     * Listar todos los representantes
     */
    async getRepresentatives(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getRepresentativesRaw(initOverrides);
    }

    /**
     * Creates request options for showRepresentative without sending the request
     */
    async showRepresentativeRequestOpts(requestParameters: AdministracinRepresentantesApiShowRepresentativeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling showRepresentative().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives/{user}`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detalle completo del representante con la lista de sus alumnos asociados (Solo Admin).
     * Ver ficha de un representante y sus representados
     */
    async showRepresentativeRaw(requestParameters: AdministracinRepresentantesApiShowRepresentativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.showRepresentativeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Detalle completo del representante con la lista de sus alumnos asociados (Solo Admin).
     * Ver ficha de un representante y sus representados
     */
    async showRepresentative(requestParameters: AdministracinRepresentantesApiShowRepresentativeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.showRepresentativeRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for storeRepresentative without sending the request
     */
    async storeRepresentativeRequestOpts(requestParameters: AdministracinRepresentantesApiStoreRepresentativeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['storeRepresentativeRequest'] == null) {
            throw new runtime.RequiredError(
                'storeRepresentativeRequest',
                'Required parameter "storeRepresentativeRequest" was null or undefined when calling storeRepresentative().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreRepresentativeRequestToJSON(requestParameters['storeRepresentativeRequest']),
        };
    }

    /**
     * Crea un nuevo usuario representante (padre o adulto) y opcionalmente le asocia y registra a su primer alumno en el dojo (Solo Admin).
     * Crear un representante
     */
    async storeRepresentativeRaw(requestParameters: AdministracinRepresentantesApiStoreRepresentativeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.storeRepresentativeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Crea un nuevo usuario representante (padre o adulto) y opcionalmente le asocia y registra a su primer alumno en el dojo (Solo Admin).
     * Crear un representante
     */
    async storeRepresentative(requestParameters: AdministracinRepresentantesApiStoreRepresentativeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.storeRepresentativeRaw(requestParameters, initOverrides);
    }

}
