/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface 0035c4e1ba50d6fdac37175767b485e4Request {
    user: number;
}

export interface B433dae97eede7cb2189397d9e23ae08Request {
    user: number;
}

/**
 * 
 */
export class AdministracinRepresentantesApi extends runtime.BaseAPI {

    /**
     * Creates request options for _0035c4e1ba50d6fdac37175767b485e4 without sending the request
     */
    async _0035c4e1ba50d6fdac37175767b485e4RequestOpts(requestParameters: 0035c4e1ba50d6fdac37175767b485e4Request): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling _0035c4e1ba50d6fdac37175767b485e4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives/{user}`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detalle completo del representante con la lista de sus alumnos asociados (Solo Admin).
     * Ver ficha de un representante y sus representados
     */
    async _0035c4e1ba50d6fdac37175767b485e4Raw(requestParameters: 0035c4e1ba50d6fdac37175767b485e4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this._0035c4e1ba50d6fdac37175767b485e4RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Detalle completo del representante con la lista de sus alumnos asociados (Solo Admin).
     * Ver ficha de un representante y sus representados
     */
    async _0035c4e1ba50d6fdac37175767b485e4(requestParameters: 0035c4e1ba50d6fdac37175767b485e4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._0035c4e1ba50d6fdac37175767b485e4Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for _4fa2d0ee6891740d98d1b69148d5891b without sending the request
     */
    async _4fa2d0ee6891740d98d1b69148d5891bRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene una lista de todos los usuarios registrados como representantes o adultos (Solo Admin).
     * Listar todos los representantes
     */
    async _4fa2d0ee6891740d98d1b69148d5891bRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this._4fa2d0ee6891740d98d1b69148d5891bRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene una lista de todos los usuarios registrados como representantes o adultos (Solo Admin).
     * Listar todos los representantes
     */
    async _4fa2d0ee6891740d98d1b69148d5891b(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._4fa2d0ee6891740d98d1b69148d5891bRaw(initOverrides);
    }

    /**
     * Creates request options for b433dae97eede7cb2189397d9e23ae08 without sending the request
     */
    async b433dae97eede7cb2189397d9e23ae08RequestOpts(requestParameters: B433dae97eede7cb2189397d9e23ae08Request): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling b433dae97eede7cb2189397d9e23ae08().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/representatives/{user}/deactivate`;
        urlPath = urlPath.replace('{user}', encodeURIComponent(String(requestParameters['user'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Suspende la cuenta de un representante y desactiva a todos sus alumnos asociados en cascada (Solo Admin).
     * Desactivar un representante y sus alumnos
     */
    async b433dae97eede7cb2189397d9e23ae08Raw(requestParameters: B433dae97eede7cb2189397d9e23ae08Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.b433dae97eede7cb2189397d9e23ae08RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Suspende la cuenta de un representante y desactiva a todos sus alumnos asociados en cascada (Solo Admin).
     * Desactivar un representante y sus alumnos
     */
    async b433dae97eede7cb2189397d9e23ae08(requestParameters: B433dae97eede7cb2189397d9e23ae08Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.b433dae97eede7cb2189397d9e23ae08Raw(requestParameters, initOverrides);
    }

}
