/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ShowStudent200Response,
    ShowStudent200ResponseFromJSON,
    ShowStudent200ResponseToJSON,
} from '../models/ShowStudent200Response';

export interface AdministracinAlumnosApiShowStudentRequest {
    student: number;
}

export interface AdministracinAlumnosApiToggleStudentStatusRequest {
    student: number;
}

export interface AdministracinAlumnosApiUpdateStudentRequest {
    student: number;
}

/**
 * 
 */
export class AdministracinAlumnosApi extends runtime.BaseAPI {

    /**
     * Creates request options for enrollStudent without sending the request
     */
    async enrollStudentRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/students`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Registra un alumno con rango manual (Solo Admin).
     * Inscribir un nuevo alumno
     */
    async enrollStudentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.enrollStudentRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registra un alumno con rango manual (Solo Admin).
     * Inscribir un nuevo alumno
     */
    async enrollStudent(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enrollStudentRaw(initOverrides);
    }

    /**
     * Creates request options for getStudents without sending the request
     */
    async getStudentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la lista completa de alumnos inscritos (Solo Admin).
     * Listar todos los alumnos
     */
    async getStudentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getStudentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene la lista completa de alumnos inscritos (Solo Admin).
     * Listar todos los alumnos
     */
    async getStudents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getStudentsRaw(initOverrides);
    }

    /**
     * Creates request options for showStudent without sending the request
     */
    async showStudentRequestOpts(requestParameters: AdministracinAlumnosApiShowStudentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['student'] == null) {
            throw new runtime.RequiredError(
                'student',
                'Required parameter "student" was null or undefined when calling showStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/students/{student}`;
        urlPath = urlPath.replace('{student}', encodeURIComponent(String(requestParameters['student'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la información de un alumno específico (Solo Admin).
     * Ver ficha de un alumno
     */
    async showStudentRaw(requestParameters: AdministracinAlumnosApiShowStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowStudent200Response>> {
        const requestOptions = await this.showStudentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowStudent200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene la información de un alumno específico (Solo Admin).
     * Ver ficha de un alumno
     */
    async showStudent(requestParameters: AdministracinAlumnosApiShowStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowStudent200Response> {
        const response = await this.showStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toggleStudentStatus without sending the request
     */
    async toggleStudentStatusRequestOpts(requestParameters: AdministracinAlumnosApiToggleStudentStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['student'] == null) {
            throw new runtime.RequiredError(
                'student',
                'Required parameter "student" was null or undefined when calling toggleStudentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/students/{student}/status`;
        urlPath = urlPath.replace('{student}', encodeURIComponent(String(requestParameters['student'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permite suspender o dar de alta a un alumno (Solo Admin).
     * Cambiar estado activo
     */
    async toggleStudentStatusRaw(requestParameters: AdministracinAlumnosApiToggleStudentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.toggleStudentStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permite suspender o dar de alta a un alumno (Solo Admin).
     * Cambiar estado activo
     */
    async toggleStudentStatus(requestParameters: AdministracinAlumnosApiToggleStudentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.toggleStudentStatusRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateStudent without sending the request
     */
    async updateStudentRequestOpts(requestParameters: AdministracinAlumnosApiUpdateStudentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['student'] == null) {
            throw new runtime.RequiredError(
                'student',
                'Required parameter "student" was null or undefined when calling updateStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/students/{student}`;
        urlPath = urlPath.replace('{student}', encodeURIComponent(String(requestParameters['student'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Actualiza los datos del alumno (Solo Admin).
     * Modificar alumno
     */
    async updateStudentRaw(requestParameters: AdministracinAlumnosApiUpdateStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateStudentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Actualiza los datos del alumno (Solo Admin).
     * Modificar alumno
     */
    async updateStudent(requestParameters: AdministracinAlumnosApiUpdateStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateStudentRaw(requestParameters, initOverrides);
    }

}
