/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetTotalStudents200Response,
    GetTotalStudents200ResponseFromJSON,
    GetTotalStudents200ResponseToJSON,
} from '../models/GetTotalStudents200Response';

/**
 * 
 */
export class AdministracinEstadsticasApi extends runtime.BaseAPI {

    /**
     * Creates request options for getActiveStudents without sending the request
     */
    async getActiveStudentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/stats/active-students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene el total de alumnos activos y su tendencia (Solo Admin).
     * Obtener alumnos activos
     */
    async getActiveStudentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTotalStudents200Response>> {
        const requestOptions = await this.getActiveStudentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTotalStudents200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene el total de alumnos activos y su tendencia (Solo Admin).
     * Obtener alumnos activos
     */
    async getActiveStudents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTotalStudents200Response> {
        const response = await this.getActiveStudentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInactiveStudents without sending the request
     */
    async getInactiveStudentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/stats/inactive-students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene el total de alumnos inactivos y su tendencia (Solo Admin).
     * Obtener alumnos inactivos
     */
    async getInactiveStudentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTotalStudents200Response>> {
        const requestOptions = await this.getInactiveStudentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTotalStudents200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene el total de alumnos inactivos y su tendencia (Solo Admin).
     * Obtener alumnos inactivos
     */
    async getInactiveStudents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTotalStudents200Response> {
        const response = await this.getInactiveStudentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTotalStudents without sending the request
     */
    async getTotalStudentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/stats/total-students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene el total de alumnos registrados y su tendencia (Solo Admin).
     * Obtener total de alumnos
     */
    async getTotalStudentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTotalStudents200Response>> {
        const requestOptions = await this.getTotalStudentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTotalStudents200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene el total de alumnos registrados y su tendencia (Solo Admin).
     * Obtener total de alumnos
     */
    async getTotalStudents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTotalStudents200Response> {
        const response = await this.getTotalStudentsRaw(initOverrides);
        return await response.value();
    }

}
