/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Login200Response,
    Login200ResponseFromJSON,
    Login200ResponseToJSON,
} from '../models/Login200Response';
import {
    type LoginRequest,
    LoginRequestFromJSON,
    LoginRequestToJSON,
} from '../models/LoginRequest';
import {
    type Logout200Response,
    Logout200ResponseFromJSON,
    Logout200ResponseToJSON,
} from '../models/Logout200Response';
import {
    type Register201Response,
    Register201ResponseFromJSON,
    Register201ResponseToJSON,
} from '../models/Register201Response';
import {
    type RegisterRequest,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
} from '../models/RegisterRequest';

export interface AutenticacinApiLoginOperationRequest {
    loginRequest: LoginRequest;
}

export interface AutenticacinApiRegisterOperationRequest {
    registerRequest: RegisterRequest;
}

/**
 * 
 */
export class AutenticacinApi extends runtime.BaseAPI {

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: AutenticacinApiLoginOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * Autentica al usuario en el sistema usando credenciales de email y contraseña, retornando un token JWT.
     * Iniciar sesión
     */
    async loginRaw(requestParameters: AutenticacinApiLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Login200Response>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Login200ResponseFromJSON(jsonValue));
    }

    /**
     * Autentica al usuario en el sistema usando credenciales de email y contraseña, retornando un token JWT.
     * Iniciar sesión
     */
    async login(requestParameters: AutenticacinApiLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Login200Response> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Invalida el token JWT del usuario autenticado.
     * Cerrar sesión
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Invalida el token JWT del usuario autenticado.
     * Cerrar sesión
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for register without sending the request
     */
    async registerRequestOpts(requestParameters: AutenticacinApiRegisterOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        };
    }

    /**
     * Permite registrar un nuevo usuario con el rol por defecto USER.
     * Registrar un nuevo usuario
     */
    async registerRaw(requestParameters: AutenticacinApiRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Register201Response>> {
        const requestOptions = await this.registerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Register201ResponseFromJSON(jsonValue));
    }

    /**
     * Permite registrar un nuevo usuario con el rol por defecto USER.
     * Registrar un nuevo usuario
     */
    async register(requestParameters: AutenticacinApiRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Register201Response> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
