/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface MisAlumnosApiShowMyStudentRequest {
    student: number;
}

/**
 * 
 */
export class MisAlumnosApi extends runtime.BaseAPI {

    /**
     * Creates request options for enrollMyStudent without sending the request
     */
    async enrollMyStudentRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permite al representante registrar a sus representados o auto-inscribirse como alumno.
     * Auto-inscribirse o inscribir un representado
     */
    async enrollMyStudentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.enrollMyStudentRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permite al representante registrar a sus representados o auto-inscribirse como alumno.
     * Auto-inscribirse o inscribir un representado
     */
    async enrollMyStudent(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enrollMyStudentRaw(initOverrides);
    }

    /**
     * Creates request options for getMyStudentsList without sending the request
     */
    async getMyStudentsListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students-list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene los alumnos asociados al representante autenticado o a sí mismo.
     * Listar mis alumnos representados
     */
    async getMyStudentsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getMyStudentsListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene los alumnos asociados al representante autenticado o a sí mismo.
     * Listar mis alumnos representados
     */
    async getMyStudentsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getMyStudentsListRaw(initOverrides);
    }

    /**
     * Creates request options for showMyStudent without sending the request
     */
    async showMyStudentRequestOpts(requestParameters: MisAlumnosApiShowMyStudentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['student'] == null) {
            throw new runtime.RequiredError(
                'student',
                'Required parameter "student" was null or undefined when calling showMyStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students/{student}`;
        urlPath = urlPath.replace('{student}', encodeURIComponent(String(requestParameters['student'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la ficha de un alumno propio o representado.
     * Ver detalle de un alumno representado
     */
    async showMyStudentRaw(requestParameters: MisAlumnosApiShowMyStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.showMyStudentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene la ficha de un alumno propio o representado.
     * Ver detalle de un alumno representado
     */
    async showMyStudent(requestParameters: MisAlumnosApiShowMyStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.showMyStudentRaw(requestParameters, initOverrides);
    }

}
