/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface 512fc0834b47f246a9c70a793486bed6Request {
    student: number;
}

/**
 * 
 */
export class MisAlumnosApi extends runtime.BaseAPI {

    /**
     * Creates request options for _0d507af438d337a3bf3a92bf89515f5f without sending the request
     */
    async _0d507af438d337a3bf3a92bf89515f5fRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permite al representante registrar a sus representados o auto-inscribirse como alumno.
     * Auto-inscribirse o inscribir un representado
     */
    async _0d507af438d337a3bf3a92bf89515f5fRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this._0d507af438d337a3bf3a92bf89515f5fRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permite al representante registrar a sus representados o auto-inscribirse como alumno.
     * Auto-inscribirse o inscribir un representado
     */
    async _0d507af438d337a3bf3a92bf89515f5f(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._0d507af438d337a3bf3a92bf89515f5fRaw(initOverrides);
    }

    /**
     * Creates request options for _512fc0834b47f246a9c70a793486bed6 without sending the request
     */
    async _512fc0834b47f246a9c70a793486bed6RequestOpts(requestParameters: 512fc0834b47f246a9c70a793486bed6Request): Promise<runtime.RequestOpts> {
        if (requestParameters['student'] == null) {
            throw new runtime.RequiredError(
                'student',
                'Required parameter "student" was null or undefined when calling _512fc0834b47f246a9c70a793486bed6().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students/{student}`;
        urlPath = urlPath.replace('{student}', encodeURIComponent(String(requestParameters['student'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la ficha de un alumno propio o representado.
     * Ver detalle de un alumno representado
     */
    async _512fc0834b47f246a9c70a793486bed6Raw(requestParameters: 512fc0834b47f246a9c70a793486bed6Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this._512fc0834b47f246a9c70a793486bed6RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene la ficha de un alumno propio o representado.
     * Ver detalle de un alumno representado
     */
    async _512fc0834b47f246a9c70a793486bed6(requestParameters: 512fc0834b47f246a9c70a793486bed6Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._512fc0834b47f246a9c70a793486bed6Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for c6342066736a9dd30cdec73bf284a791 without sending the request
     */
    async c6342066736a9dd30cdec73bf284a791RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students-list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene los alumnos asociados al representante autenticado o a sí mismo.
     * Listar mis alumnos representados
     */
    async c6342066736a9dd30cdec73bf284a791Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.c6342066736a9dd30cdec73bf284a791RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtiene los alumnos asociados al representante autenticado o a sí mismo.
     * Listar mis alumnos representados
     */
    async c6342066736a9dd30cdec73bf284a791(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.c6342066736a9dd30cdec73bf284a791Raw(initOverrides);
    }

}
