/* tslint:disable */
/* eslint-disable */
/**
 * Minarai Dojo API
 * API de gestión para Dojo de Karate - Pagos y Autenticación
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreatePayment201Response,
    CreatePayment201ResponseFromJSON,
    CreatePayment201ResponseToJSON,
} from '../models/CreatePayment201Response';
import {
    type GetMyStudents200Response,
    GetMyStudents200ResponseFromJSON,
    GetMyStudents200ResponseToJSON,
} from '../models/GetMyStudents200Response';
import {
    type GetPayments200Response,
    GetPayments200ResponseFromJSON,
    GetPayments200ResponseToJSON,
} from '../models/GetPayments200Response';
import {
    type ShowPayment200Response,
    ShowPayment200ResponseFromJSON,
    ShowPayment200ResponseToJSON,
} from '../models/ShowPayment200Response';
import {
    type VerifyPayment200Response,
    VerifyPayment200ResponseFromJSON,
    VerifyPayment200ResponseToJSON,
} from '../models/VerifyPayment200Response';
import {
    type VerifyPaymentRequest,
    VerifyPaymentRequestFromJSON,
    VerifyPaymentRequestToJSON,
} from '../models/VerifyPaymentRequest';

export interface PagosApiCreatePaymentRequest {
    studentId: number;
    amount: number;
    paymentDate: Date;
    paymentMethod: string;
    referenceNumber?: string | null;
    receipt?: Blob;
}

export interface PagosApiGetPaymentsRequest {
    status?: GetPaymentsStatusEnum;
}

export interface PagosApiShowPaymentRequest {
    payment: number;
}

export interface PagosApiVerifyPaymentOperationRequest {
    payment: number;
    verifyPaymentRequest: VerifyPaymentRequest;
}

/**
 * 
 */
export class PagosApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPayment without sending the request
     */
    async createPaymentRequestOpts(requestParameters: PagosApiCreatePaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['studentId'] == null) {
            throw new runtime.RequiredError(
                'studentId',
                'Required parameter "studentId" was null or undefined when calling createPayment().'
            );
        }

        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling createPayment().'
            );
        }

        if (requestParameters['paymentDate'] == null) {
            throw new runtime.RequiredError(
                'paymentDate',
                'Required parameter "paymentDate" was null or undefined when calling createPayment().'
            );
        }

        if (requestParameters['paymentMethod'] == null) {
            throw new runtime.RequiredError(
                'paymentMethod',
                'Required parameter "paymentMethod" was null or undefined when calling createPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['studentId'] != null) {
            formParams.append('student_id', requestParameters['studentId'] as any);
        }

        if (requestParameters['amount'] != null) {
            formParams.append('amount', requestParameters['amount'] as any);
        }

        if (requestParameters['paymentDate'] != null) {
            formParams.append('payment_date', requestParameters['paymentDate'] as any);
        }

        if (requestParameters['paymentMethod'] != null) {
            formParams.append('payment_method', requestParameters['paymentMethod'] as any);
        }

        if (requestParameters['referenceNumber'] != null) {
            formParams.append('reference_number', requestParameters['referenceNumber'] as any);
        }

        if (requestParameters['receipt'] != null) {
            formParams.append('receipt', requestParameters['receipt'] as any);
        }


        let urlPath = `/api/payments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Permite a un alumno o representante registrar un nuevo pago adjuntando opcionalmente el comprobante digital (imagen o PDF).
     * Registrar un pago
     */
    async createPaymentRaw(requestParameters: PagosApiCreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePayment201Response>> {
        const requestOptions = await this.createPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePayment201ResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un alumno o representante registrar un nuevo pago adjuntando opcionalmente el comprobante digital (imagen o PDF).
     * Registrar un pago
     */
    async createPayment(requestParameters: PagosApiCreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePayment201Response> {
        const response = await this.createPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyStudents without sending the request
     */
    async getMyStudentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/my-students`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la lista de los alumnos que el usuario logueado puede gestionar (él mismo si es alumno activo, o sus representados).
     * Listar alumnos relacionados
     */
    async getMyStudentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMyStudents200Response>> {
        const requestOptions = await this.getMyStudentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMyStudents200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene la lista de los alumnos que el usuario logueado puede gestionar (él mismo si es alumno activo, o sus representados).
     * Listar alumnos relacionados
     */
    async getMyStudents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMyStudents200Response> {
        const response = await this.getMyStudentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPayments without sending the request
     */
    async getPaymentsRequestOpts(requestParameters: PagosApiGetPaymentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la lista de pagos registrados. Los administradores ven todos los pagos (con filtro opcional por estado). Los usuarios estándar ven solo sus pagos y los de sus representados.
     * Listar pagos
     */
    async getPaymentsRaw(requestParameters: PagosApiGetPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPayments200Response>> {
        const requestOptions = await this.getPaymentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPayments200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene la lista de pagos registrados. Los administradores ven todos los pagos (con filtro opcional por estado). Los usuarios estándar ven solo sus pagos y los de sus representados.
     * Listar pagos
     */
    async getPayments(requestParameters: PagosApiGetPaymentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPayments200Response> {
        const response = await this.getPaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for showPayment without sending the request
     */
    async showPaymentRequestOpts(requestParameters: PagosApiShowPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['payment'] == null) {
            throw new runtime.RequiredError(
                'payment',
                'Required parameter "payment" was null or undefined when calling showPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/payments/{payment}`;
        urlPath = urlPath.replace('{payment}', encodeURIComponent(String(requestParameters['payment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene la información detallada de un pago específico. Requiere permisos (ser el propietario, el representante del alumno, o administrador).
     * Ver detalle de un pago
     */
    async showPaymentRaw(requestParameters: PagosApiShowPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowPayment200Response>> {
        const requestOptions = await this.showPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowPayment200ResponseFromJSON(jsonValue));
    }

    /**
     * Obtiene la información detallada de un pago específico. Requiere permisos (ser el propietario, el representante del alumno, o administrador).
     * Ver detalle de un pago
     */
    async showPayment(requestParameters: PagosApiShowPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowPayment200Response> {
        const response = await this.showPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyPayment without sending the request
     */
    async verifyPaymentRequestOpts(requestParameters: PagosApiVerifyPaymentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['payment'] == null) {
            throw new runtime.RequiredError(
                'payment',
                'Required parameter "payment" was null or undefined when calling verifyPayment().'
            );
        }

        if (requestParameters['verifyPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyPaymentRequest',
                'Required parameter "verifyPaymentRequest" was null or undefined when calling verifyPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/payments/{payment}/verify`;
        urlPath = urlPath.replace('{payment}', encodeURIComponent(String(requestParameters['payment'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyPaymentRequestToJSON(requestParameters['verifyPaymentRequest']),
        };
    }

    /**
     * Permite a un administrador aprobar o rechazar un pago. Si se aprueba, se genera automáticamente el recibo.
     * Verificar pago (Administrador)
     */
    async verifyPaymentRaw(requestParameters: PagosApiVerifyPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyPayment200Response>> {
        const requestOptions = await this.verifyPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyPayment200ResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un administrador aprobar o rechazar un pago. Si se aprueba, se genera automáticamente el recibo.
     * Verificar pago (Administrador)
     */
    async verifyPayment(requestParameters: PagosApiVerifyPaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyPayment200Response> {
        const response = await this.verifyPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetPaymentsStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;
export type GetPaymentsStatusEnum = typeof GetPaymentsStatusEnum[keyof typeof GetPaymentsStatusEnum];
